### ISSUE TITLE
Potential Problem in Mann-Whitney U Test 

### ISSUE THREAD

**Issue by hl-xue** [astronights/hypors#1]
Hello,

Thanks for extending Rust to hypothesis testing !

I am using the Mann-Whitney U test under hypors version 0.2.3 [here](https://crates.io/crates/hypors), and found the results are not consistent with what I got with Python.
Also, when I did:
```Rust
fn test_mannwhitneyu_pval() {
    let vals1 = Series::new("group1".into(), vec![1f64, 2f64, 3f64, 4f64, 5f64]);
    let tail = hypors::common::TailType::Two;
    println!("{:?}", u_test(&vals1, &vals1, 0.05, tail));
}
```
It gives:
```
Ok(TestResult { test_statistic: 10.0, p_value: 0.6015081344405899, confidence_interval: (NaN, NaN), null_hypothesis: "H0: The distributions of both groups are equal.", alt_hypothesis: "Ha: The distributions of both groups are not equal.", reject_null: false })
```
While I was expecting the p-value being 1.0, so as given by Python:
```Python
>>> from scipy.stats import mannwhitneyu
>>> mannwhitneyu([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
MannwhitneyuResult(statistic=12.5, pvalue=1.0)
```

Is this a problem, or maybe I misunderstood something?

Thanks again!

Kind regards.

**Comment by astronights** [comment]
Hey thanks for pointing this out! I realized I missed out on the rank tie calculation on the `mann_whitney/u.rs` file.  The fix has been done and I've just published the fix in `v0.2.4`. 

If you see any further issues (although I hope not many), feel free to raise them or open PRs (if you'd like to contribute). Happy to help.

**Comment by hl-xue** [comment]
Oh, that's so fast! Thank you very much!
Kind regards.

**Comment by astronights** [comment]
No worries. If all looks good, we can close the issue as well. Thanks!

**Comment by hl-xue** [comment]
Yes, thanks!
